### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Sofia-vig** [Marcosreuquen/apx-desafio-m5#1]
Hola Marcoss! Re bien, me re gusto el codigo. Lo unico fijate que:
- Cuando no elijo ninguna mano deberia redireccionarme a la pagina principal, o al tutorial y no llegar a mostrarme la jugada. 
- No se esta guardando en el local storage, si salgo y entro de la pagina lo que es la puntuacion deberia estar como la ultima vez que jugue mas los nuevos puntos que haga jugando. Fijate si podes corregirle eso!!

**Comment by Marcosreuquen** [comment]
Buenas, Sofi. 
Ahí le arreglé ambas cosas y también un error de maquetado que le descubrí en page result. Envío de nuevo el link. Mil gracias!
